version: "3.8"
services:
  app:
    build:
      context: .
      target: runtime
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      # You can override any env var here, e.g.:
      # GEMINI_API_KEY: your_key_here
      # SESSION_SECRET: your_secret_here
    restart: unless-stopped
